### ISSUE TITLE
Alignment for dropdown

### ISSUE THREAD

**Issue by BasselArt** [pishran/nova-rtl-theme#3]
Thanks for the great theme, I have a small issue and can't fix it, some dropdown not viewed correctly,
attached a screenshot to describe the issue.
I have a custom CSS file but I need some tips to fixe this.

Regards.

![Screen Shot 2019-11-03 at 8 25 10 AM](https://user-images.githubusercontent.com/5476744/68080815-f9c85400-fe13-11e9-918c-a78c266a80a1.png)
![Screen Shot 2019-11-03 at 8 25 16 AM](https://user-images.githubusercontent.com/5476744/68080816-f9c85400-fe13-11e9-8c42-1c842e285c5a.png)
![Screen Shot 2019-11-03 at 8 24 55 AM](https://user-images.githubusercontent.com/5476744/68080817-fa60ea80-fe13-11e9-9a92-bbfbc79f74a1.png)

**Comment by FaridAghili** [comment]
Yes, already noticed that, didn't find a fix though.
Feel free to make a PR.

**Comment by sepehrr** [comment]
this problem is because of `popper.js`.
do this to solve the problem (assuming nova resides in `/nova/`):
1. change 'bottom-end' to 'bottom-start' in `/nova/resource/js/components/Dropdown.vue`
2. change 'bottom-start' to 'bottom-end' in `/nova/resource/js/components/SearchInput.vue`
3. change 'bottom-start' to 'bottom-end' in `/nova/resource/js/views/Index.vue`
5. make a `webpack.mix.js` file in your nova folder. (duplicate `/nova/webpack.mix.js.dist` to `/nova/webpack.mix.js` is just ok)
6. `cd nova`
6. run `npm install`
7. run `npm run prod`
8. now in laravel folder run `php artisan nova:publish`

now your Nova is RTL-friendly!

**Comment by FaridAghili** [comment]
@sepehrr 
Thank you for explanation, it works but can't be used cause we need a way to implement it in our package.
Editing Nova's source is not an option.

**Comment by SadeghPM** [comment]
> Yes, already noticed that, didn't find a fix though.
> Feel free to make a PR.

this fix issue in any screen size:
```css
div.tooltip[x-placement="top-start"],div.tooltip[x-placement="bottom-start"]{
    left: 220px !important;
}
div.tooltip[x-placement="top-end"],div.tooltip[x-placement="bottom-end"]{
    left: -200px !important;
}
```
