### ISSUE TITLE
Few missing RTL edits

### ISSUE THREAD

**Issue by kfirba** [pishran/nova-rtl-theme#6]
Hey,

I've submitted a PR that fixes the Dropdowns alignment. As part of the work to ensure the dropdowns work as expected, I've encountered a few issues:

1. The lenses view has its back arrow in the wrong direction:
![image](https://user-images.githubusercontent.com/8510486/74529659-1f93e780-4f31-11ea-9273-1b840d99fc95.png)

2. The currently authenticated user dropdown  has `left: 112px !important` injected via a custom <style> tag:

```css
<style type="text/css">#popover_04d1sugnm5{left: 112px !important;}</style>
```

![image](https://user-images.githubusercontent.com/8510486/74529808-45b98780-4f31-11ea-8187-637d37d8334c.png)

I could not find which component injects this.  We need to set it to `left: 0` and the dropdown aligns itself just perfectly.
